### ISSUE TITLE
How to listen for updates from a different game object ref?

### ISSUE THREAD

**Issue by Q16solver** [laineus/phavuer#2]
Hello!

I don’t directly use this library but I was trying to make my own version and referencing this along the way (it helps so much so thank you for making this incredible library!). While I was looking through the Libra game that referenced this library I noticed there was no use of ‘computed’ that listens to another game object reference e.g.

const newItemX = computed(() => imageGameObject.value.x + imageGameObject.value.displayWidth)

this actually doesn’t update after the displayWidth is changed since it occurs inside phaser and vue has no idea, how do we accomplish something like this?

**Comment by laineus** [comment]
@Q16solver Hello!

If you want to listen the position of a gameObject using something like computed, it is recommended to use v-model.
At the time of creating 'The Dream Libra had', this feature was not available, but the current Phavuer supports v-model.

Additionally, in the source of 'The Dream Libra had', it directly references GameObjects of other components, but this is not recommended.
If the data interacts outside of the component, it's better to separate it as a different store.

```
// playerData.js

export default reactive({ x: 0, y: 0 })
```

```
Character.vue

<script setup>
import playerData from 'playerData.js'
</script>

<template>
  <Image v-model:x="playerData.x" v-model:y="playerData.y" />
</template>
```

```
UI.vue

<script setup>
import playerData from 'playerData.js'
const isSomething = computed(() => playerData.x === 0 && playerData.y === 0)
</script>
```

(Not tested)

[This repository](https://github.com/laineus/phavuer-example) is designed with stores pattern, so you should refer it instead of libra.

Thank you.

**Comment by laineus** [comment]
To see how Phavuer makes the properties of Phaser's GameObject reactive, please look here.
https://github.com/laineus/phavuer/blob/master/src/setters.js#L27

**Comment by Q16solver** [comment]
Yeah sweet! I tried it out, and it's pretty much working for the most part, I'm only experiencing one issue, which is that I can't seem to call emit inside watch hook, e.g. https://github.com/Esposter/Esposter/blob/main/lib/phaser/composables/useInitializeGameObjectSetters.ts
it seems to be giving me a bunch of issues with `An error occurred in hook 'walkComponentParents' with payload:` most likely not being able to find the vue instance, I'm not exactly sure why your setter is able to use the emit in the watch hook

**Comment by Q16solver** [comment]
Oh wait, I get it, you already pass the emit to the setter before it’s in the watch, perfect, I’ll try it tmr and see if that works

**Comment by laineus** [comment]
ありがとう！
